export const ACADEMY_LIST_REQUEST = 'ACADEMY_LIST_REQUEST';
export const ACADEMY_LIST_SUCCESS = 'ACADEMY_LIST_SUCCESS';
export const ACADEMY_LIST_FAIL = 'ACADEMY_LIST_FAIL';

export const ACADEMY_DETAILS_REQUEST = 'ACADEMY_DETAILS_REQUEST';
export const ACADEMY_DETAILS_SUCCESS = 'ACADEMY_DETAILS_SUCCESS';
export const ACADEMY_DETAILS_FAIL = 'ACADEMY_DETAILS_FAIL';

export const ACADEMY_BY_PIANO_REQUEST = 'ACADEMY_BY_PIANO_REQUEST';
export const ACADEMY_BY_PIANO_SUCCESS = 'ACADEMY_BY_PIANO_SUCCESS';
export const ACADEMY_BY_PIANO_FAIL = 'ACADEMY_BY_PIANO_FAIL';
