export const PIANO_LIST_REQUEST = 'PIANO_LIST_REQUEST';
export const PIANO_LIST_SUCCESS = 'PIANO_LIST_SUCCESS';
export const PIANO_LIST_FAIL = 'PIANO_LIST_FAIL';

export const PIANO_DETAILS_REQUEST = 'PIANO_DETAILS_REQUEST';
export const PIANO_DETAILS_SUCCESS = 'PIANO_DETAILS_SUCCESS';
export const PIANO_DETAILS_FAIL = 'PIANO_DETAILS_FAIL';

export const PIANO_BY_ACADEMY_REQUEST = 'PIANO_BY_ACADEMY_REQUEST';
export const PIANO_BY_ACADEMY_SUCCESS = 'PIANO_BY_ACADEMY_SUCCESS';
export const PIANO_BY_ACADEMY_FAIL = 'PIANO_BY_ACADEMY_FAIL';
